export const data = [
    {
        "id": "0",
        "idHex": "00",
        "decCn": "支持的PID",
        "decEn": "PIDs supported [01 - 20]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $01..PID $20]"
    },
    {
        "id": "1",
        "idHex": "01",
        "decCn": "自诊断故障码清除后的监视状态",
        "decEn": "Monitor status since DTCs cleared",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded."
    },
    {
        "id": "2",
        "idHex": "02",
        "decCn": "导致冻结帧数据存储的故障码",
        "decEn": "Freeze DTC",
        "decLen": "2",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "3",
        "idHex": "03",
        "decCn": "燃油系统 1 状态 ",
        "decEn": "Fuel system status",
        "decLen": "2",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded."
    },
    {
        "id": "4",
        "idHex": "04",
        "decCn": "计算负荷值 ",
        "decEn": "Calculated engine load",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "5",
        "idHex": "05",
        "decCn": "发动机冷却液温度",
        "decEn": "Engine coolant temperature",
        "decLen": "1",
        "valueMin": "-40",
        "valueMax": "215",
        "units": "°C",
        "formula": "A-40"
    },
    {
        "id": "6",
        "idHex": "06",
        "decCn": "短期燃油修正-组 1 短期燃油修正-组 3",
        "decEn": "Short term fuel trim—Bank 1",
        "decLen": "1",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100"
    },
    {
        "id": "7",
        "idHex": "07",
        "decCn": "长期燃油修正-组 1 长期燃油修正-组 3",
        "decEn": "Long term fuel trim—Bank 1",
        "decLen": "1",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100"
    },
    {
        "id": "8",
        "idHex": "08",
        "decCn": "短期燃油修正-组 2 短期燃油修正-组 4",
        "decEn": "Short term fuel trim—Bank 2",
        "decLen": "1",
        "valueMin": "-101",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100"
    },
    {
        "id": "9",
        "idHex": "09",
        "decCn": "长期燃油修正-组 2 长期燃油修正-组 4",
        "decEn": "Long term fuel trim—Bank 2",
        "decLen": "1",
        "valueMin": "-102",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100"
    },
    {
        "id": "10",
        "idHex": "0A",
        "decCn": "燃油轨压力（表压力） ",
        "decEn": "Fuel pressure (gauge pressure)",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "765",
        "units": "kPa",
        "formula": "3A"
    },
    {
        "id": "11",
        "idHex": "0B",
        "decCn": "进气歧管绝对压力 ",
        "decEn": "Intake manifold absolute pressure",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "255",
        "units": "kPa",
        "formula": "A"
    },
    {
        "id": "12",
        "idHex": "0C",
        "decCn": "发动机转速",
        "decEn": "Engine RPM",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "16384",
        "units": "rpm",
        "formula": "(256A+B)/4"
    },
    {
        "id": "13",
        "idHex": "0D",
        "decCn": "车速传感器",
        "decEn": "Vehicle speed",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "255",
        "units": "km/h",
        "formula": "A"
    },
    {
        "id": "14",
        "idHex": "0E",
        "decCn": "1号缸点火提前角 ",
        "decEn": "Timing advance",
        "decLen": "1",
        "valueMin": "-64",
        "valueMax": "64",
        "units": "° before T",
        "formula": "A/2-64"
    },
    {
        "id": "15",
        "idHex": "0F",
        "decCn": "进气温度",
        "decEn": "Intake air temperature",
        "decLen": "1",
        "valueMin": "-40",
        "valueMax": "215",
        "units": "°C",
        "formula": "A-40"
    },
    {
        "id": "16",
        "idHex": "10",
        "decCn": "质量空气流量传感器的空气流量",
        "decEn": "MAF air flow rate",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "655",
        "units": "grams/sec",
        "formula": "(256A+B)/100"
    },
    {
        "id": "17",
        "idHex": "11",
        "decCn": "绝对节气门位置",
        "decEn": "Throttle position",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "18",
        "idHex": "12",
        "decCn": "指令二次空气喷射系统状态",
        "decEn": "Commanded secondary air status",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded."
    },
    {
        "id": "19",
        "idHex": "13",
        "decCn": "氧传感器位置",
        "decEn": "Oxygen sensors present (in 2 banks)",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "[A0..A3] == Bank 1, Sensors 1-4. [A4..A7] == Bank 2..."
    },
    {
        "id": "20",
        "idHex": "14",
        "decCn": "B1-S1",
        "decEn": "Oxygen Sensor 1,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-100(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "21",
        "idHex": "15",
        "decCn": "B1-S2",
        "decEn": "Oxygen Sensor 2,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-101(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "22",
        "idHex": "16",
        "decCn": "B1-S3,B2-S1",
        "decEn": "Oxygen Sensor 3,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-102(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "23",
        "idHex": "17",
        "decCn": "B1-S4,B2-S2",
        "decEn": "Oxygen Sensor 4,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-103(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "24",
        "idHex": "18",
        "decCn": "B2-S1,B3-S1",
        "decEn": "Oxygen Sensor 5,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-104(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "25",
        "idHex": "19",
        "decCn": "B2-S2,B3-S2",
        "decEn": "Oxygen Sensor 6,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-105(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "26",
        "idHex": "1A",
        "decCn": "B2-S3,B4-S1",
        "decEn": "Oxygen Sensor 7,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-106(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "27",
        "idHex": "1B",
        "decCn": "B2-S4,B4-S2",
        "decEn": "Oxygen Sensor 8,A: Voltage,B: Short term fuel trim",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "127599",
        "units": "volts%",
        "formula": "A/200,100B/128-107(if B==$FF, sensor is not used in trim calculation)"
    },
    {
        "id": "28",
        "idHex": "1C",
        "decCn": "车辆或发动机符合哪个\nOBD 要求",
        "decEn": "OBD standards this vehicle conforms to",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded."
    },
    {
        "id": "29",
        "idHex": "1D",
        "decCn": "氧传感器位置",
        "decEn": "Oxygen sensors present (in 4 banks)",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Similar to PID 13, but [A0..A7] == [B1S1, B1S2, B2S1, B2S2, B3S1, B3S2, B4S1, B4S2]"
    },
    {
        "id": "30",
        "idHex": "1E",
        "decCn": "辅助输入状态",
        "decEn": "Auxiliary input status",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "A0 == Power Take Off (PTO) status (1 == active)[A1..A7] not used"
    },
    {
        "id": "31",
        "idHex": "1F",
        "decCn": "自发动机启动的时间",
        "decEn": "Run time since engine start",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "65535",
        "units": "seconds",
        "formula": "256A+B"
    },
    {
        "id": "32",
        "idHex": "20",
        "decCn": "",
        "decEn": "PIDs supported [21 - 40]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $21..PID $40]"
    },
    {
        "id": "33",
        "idHex": "21",
        "decCn": "当故障指示灯激活时的行\n程",
        "decEn": "Distance traveled with malfunction indicator lamp (MIL) on",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "65535",
        "units": "km",
        "formula": "256A+B"
    },
    {
        "id": "34",
        "idHex": "22",
        "decCn": "相对于歧管真空的油轨\n压力",
        "decEn": "Fuel Rail Pressure (relative to manifold vacuum)",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "5177",
        "units": "kPa",
        "formula": "0.079(256A+B)"
    },
    {
        "id": "35",
        "idHex": "23",
        "decCn": "油轨压力 ",
        "decEn": "Fuel Rail Gauge Pressure (diesel, or gasoline direct injection)",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "655350",
        "units": "kPa",
        "formula": "10(256A+B)"
    },
    {
        "id": "36",
        "idHex": "24",
        "decCn": "B1-S1（宽域 O2S）",
        "decEn": "Oxygen Sensor 1,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "37",
        "idHex": "25",
        "decCn": "B1-S2（宽域 O2S）",
        "decEn": "Oxygen Sensor 2,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "1",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "38",
        "idHex": "26",
        "decCn": "B1-S3（宽域 O2S）,B2-S1（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 3,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "2",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "39",
        "idHex": "27",
        "decCn": "B1-S4（宽域 O2S）,B2-S2（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 4,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "3",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "40",
        "idHex": "28",
        "decCn": "B2-S1（宽域 O2S）,B3-S1（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 5,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "4",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "41",
        "idHex": "29",
        "decCn": "B2-S2（宽域 O2S）,B3-S2（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 6,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "5",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "42",
        "idHex": "2A",
        "decCn": "B2-S3（宽域 O2S）,B4-S1（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 7,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "6",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "43",
        "idHex": "2B",
        "decCn": "B2-S4（宽域 O2S）,B4-S2（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 8,AB: Fuel–Air Equivalence Ratio,CD: Voltage",
        "decLen": "4",
        "valueMin": "7",
        "valueMax": "28",
        "units": "ratio V",
        "formula": "2(256A+B)/65536,2(256C+D)/65536"
    },
    {
        "id": "44",
        "idHex": "2C",
        "decCn": "指令 EGR ",
        "decEn": "Commanded EGR",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "45",
        "idHex": "2D",
        "decCn": "EGR 误差",
        "decEn": "EGR Error",
        "decLen": "1",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100"
    },
    {
        "id": "46",
        "idHex": "2E",
        "decCn": "指令燃油蒸发\n净化",
        "decEn": "Commanded evaporative purge",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "47",
        "idHex": "2F",
        "decCn": "油 位 输 入\n（FLI）",
        "decEn": "Fuel Tank Level Input",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "48",
        "idHex": "30",
        "decCn": "故障码清除后",
        "decEn": "Warm-ups since codes cleared",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "255",
        "units": "count",
        "formula": "A"
    },
    {
        "id": "49",
        "idHex": "31",
        "decCn": "故障码清除后\n的行驶距离",
        "decEn": "Distance traveled since codes cleared",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "65535",
        "units": "km",
        "formula": "256A+B"
    },
    {
        "id": "50",
        "idHex": "32",
        "decCn": "蒸气排放系统\n的蒸气压",
        "decEn": "Evap. System Vapor Pressure",
        "decLen": "2",
        "valueMin": "-8192",
        "valueMax": "8192",
        "units": "Pa",
        "formula": "(256A+B)/4(AB is two's complement signed)"
    },
    {
        "id": "51",
        "idHex": "33",
        "decCn": "大气压力 ",
        "decEn": "Absolute Barometric Pressure",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "255",
        "units": "kPa",
        "formula": "A"
    },
    {
        "id": "52",
        "idHex": "34",
        "decCn": "B1-S1（宽域 O2S）",
        "decEn": "Oxygen Sensor 1,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "53",
        "idHex": "35",
        "decCn": "B1-S2（宽域 O2S）",
        "decEn": "Oxygen Sensor 2,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "54",
        "idHex": "36",
        "decCn": "B1-S3（宽域 O2S）,B2-S1（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 3,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "55",
        "idHex": "37",
        "decCn": "B1-S4（宽域 O2S）,B2-S2（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 4,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "56",
        "idHex": "38",
        "decCn": "B2-S1（宽域 O2S）,B3-S1（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 5,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "57",
        "idHex": "39",
        "decCn": "B2-S2（宽域 O2S）,B3-S2（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 6,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "58",
        "idHex": "3A",
        "decCn": "B2-S3（宽域 O2S）,B4-S1（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 7,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "59",
        "idHex": "3B",
        "decCn": "B2-S4（宽域 O2S）,B4-S2（宽域 O2S）（3 或 4 组）",
        "decEn": "Oxygen Sensor 8,AB: Fuel–Air Equivalence Ratio,CD: Current",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2128",
        "units": "ratio mA",
        "formula": "2(256A+B)/65536,(256C+D)/256-128"
    },
    {
        "id": "60",
        "idHex": "3C",
        "decCn": "催化器温度\nB1，S1",
        "decEn": "Catalyst Temperature: Bank 1, Sensor 1",
        "decLen": "2",
        "valueMin": "-40",
        "valueMax": "6514",
        "units": "°C",
        "formula": "(256A+B)/10-40"
    },
    {
        "id": "61",
        "idHex": "3D",
        "decCn": "催化器温度\nB2，S1",
        "decEn": "Catalyst Temperature: Bank 2, Sensor 1",
        "decLen": "2",
        "valueMin": "-40",
        "valueMax": "6514",
        "units": "°C",
        "formula": ""
    },
    {
        "id": "62",
        "idHex": "3E",
        "decCn": "催化器温度\nB1，S2",
        "decEn": "Catalyst Temperature: Bank 1, Sensor 2",
        "decLen": "2",
        "valueMin": "-40",
        "valueMax": "6514",
        "units": "°C",
        "formula": ""
    },
    {
        "id": "63",
        "idHex": "3F",
        "decCn": "催化器温度 ",
        "decEn": "Catalyst Temperature: Bank 2, Sensor 2",
        "decLen": "2",
        "valueMin": "-40",
        "valueMax": "6514",
        "units": "°C",
        "formula": ""
    },
    {
        "id": "64",
        "idHex": "40",
        "decCn": "",
        "decEn": "PIDs supported [41 - 60]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $41..PID $60]"
    },
    {
        "id": "65",
        "idHex": "41",
        "decCn": "当前驾驶循环监视状态",
        "decEn": "Monitor status this drive cycle",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded."
    },
    {
        "id": "66",
        "idHex": "42",
        "decCn": "控制模块电压",
        "decEn": "Control module voltage",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "66",
        "units": "V",
        "formula": "(256A+B)/1000"
    },
    {
        "id": "67",
        "idHex": "43",
        "decCn": "绝对负荷值",
        "decEn": "Absolute load value",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "25700",
        "units": "%",
        "formula": "100(256A+B)/255"
    },
    {
        "id": "68",
        "idHex": "44",
        "decCn": "燃/空（F/A）指\n令当量比",
        "decEn": "Fuel–Air commanded equivalence ratio",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "2",
        "units": "ratio",
        "formula": "2(256A+B)/65536"
    },
    {
        "id": "69",
        "idHex": "45",
        "decCn": "相对节气门位\n置",
        "decEn": "Relative throttle position",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "70",
        "idHex": "46",
        "decCn": "周围空气温度\n（ 与 IAT-S0F\n的换算比例相\n同）",
        "decEn": "Ambient air temperature",
        "decLen": "1",
        "valueMin": "-40",
        "valueMax": "215",
        "units": "°C",
        "formula": "A-40"
    },
    {
        "id": "71",
        "idHex": "47",
        "decCn": "绝对节气门位\n置 B",
        "decEn": "Absolute throttle position B",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "72",
        "idHex": "48",
        "decCn": "绝对节气门位\n置 C",
        "decEn": "Absolute throttle position C",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/256"
    },
    {
        "id": "73",
        "idHex": "49",
        "decCn": "加速踏板位置 D ",
        "decEn": "Accelerator pedal position D",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/257"
    },
    {
        "id": "74",
        "idHex": "4A",
        "decCn": "加速踏板位置 E ",
        "decEn": "Accelerator pedal position E",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/258"
    },
    {
        "id": "75",
        "idHex": "4B",
        "decCn": "加速踏板位置 F ",
        "decEn": "Accelerator pedal position F",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/259"
    },
    {
        "id": "76",
        "idHex": "4C",
        "decCn": "节气门执行器控制\n（TAC）指令",
        "decEn": "Commanded throttle actuator",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/260"
    },
    {
        "id": "77",
        "idHex": "4D",
        "decCn": "至故障指示灯激活时引擎\n运转时间",
        "decEn": "Time run with MIL on",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "65535",
        "units": "minutes",
        "formula": "256A+B"
    },
    {
        "id": "78",
        "idHex": "4E",
        "decCn": "至故障码清除时引擎运转\n时间",
        "decEn": "Time since trouble codes cleared",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "65535",
        "units": "minutes",
        "formula": "256A+B"
    },
    {
        "id": "79",
        "idHex": "4F",
        "decCn": "外部测试设备配置信息#1",
        "decEn": "Maximum value for Fuel–Air equivalence ratio, oxygen sensor voltage, oxygen sensor current, and intake manifold absolute pressure",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2147483647",
        "units": "ratio, V, ",
        "formula": "A, B, C, D*10"
    },
    {
        "id": "80",
        "idHex": "50",
        "decCn": "外部测试设备配置信息#2 ",
        "decEn": "Maximum value for air flow rate from mass air flow sensor",
        "decLen": "4",
        "valueMin": "0",
        "valueMax": "2550",
        "units": "g/s",
        "formula": "A*10, B, C, and D are reserved for future use"
    },
    {
        "id": "81",
        "idHex": "51",
        "decCn": "车辆当前所用燃油类型",
        "decEn": "Fuel Type",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "From fuel type table"
    },
    {
        "id": "82",
        "idHex": "52",
        "decCn": "燃料中酒精含量",
        "decEn": "Ethanol fuel %",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "83",
        "idHex": "53",
        "decCn": "燃油蒸发系统绝对蒸气\n压力",
        "decEn": "Absolute Evap system Vapor Pressure",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "328",
        "units": "kPa",
        "formula": "(256A+B)/200"
    },
    {
        "id": "84",
        "idHex": "54",
        "decCn": "燃油蒸发系统蒸气压力",
        "decEn": "Evap system vapor pressure",
        "decLen": "2",
        "valueMin": "-32767",
        "valueMax": "32768",
        "units": "Pa",
        "formula": "((A*256)+B)-32767"
    },
    {
        "id": "85",
        "idHex": "55",
        "decCn": "短期辅助氧传感器燃油\n修正－B1（适用于仅有\n一个燃油修正值的情况）,B3",
        "decEn": "Short term secondary oxygen sensor trim, A: bank 1, B: bank 3",
        "decLen": "2",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100,100B/128-100"
    },
    {
        "id": "86",
        "idHex": "56",
        "decCn": "长期辅助氧传感器燃油\n修正－B1（适用于仅有\n一个燃油修正值的情况）,B3",
        "decEn": "Long term secondary oxygen sensor trim, A: bank 1, B: bank 3",
        "decLen": "2",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100,100B/128-100"
    },
    {
        "id": "87",
        "idHex": "57",
        "decCn": "短期辅助氧传感器燃油\n修正－B2（适用于仅有\n一个燃油修正值的情况）,B4",
        "decEn": "Short term secondary oxygen sensor trim, A: bank 2, B: bank 4",
        "decLen": "2",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100,100B/128-100"
    },
    {
        "id": "88",
        "idHex": "58",
        "decCn": "长期辅助氧传感器燃油\n修正－B2（适用于仅有\n一个燃油修正值的情况）,B4",
        "decEn": "Long term secondary oxygen sensor trim, A: bank 2, B: bank 4",
        "decLen": "2",
        "valueMin": "-100",
        "valueMax": "99",
        "units": "%",
        "formula": "100A/128-100,100B/128-100"
    },
    {
        "id": "89",
        "idHex": "59",
        "decCn": "油轨压力\n（绝对）",
        "decEn": "Fuel rail absolute pressure",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "655350",
        "units": "kPa",
        "formula": "10(256A+B)"
    },
    {
        "id": "90",
        "idHex": "5A",
        "decCn": "相对加速踏板\n位置",
        "decEn": "Relative accelerator pedal position",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "91",
        "idHex": "5B",
        "decCn": "混合动力车辆\n电池组剩余寿\n命",
        "decEn": "Hybrid battery pack remaining life",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": "100A/255"
    },
    {
        "id": "92",
        "idHex": "5C",
        "decCn": "发动机机油温\n度",
        "decEn": "Engine oil temperature",
        "decLen": "1",
        "valueMin": "-40",
        "valueMax": "210",
        "units": "°C",
        "formula": "A-40"
    },
    {
        "id": "93",
        "idHex": "5D",
        "decCn": "燃油喷射正时 ",
        "decEn": "Fuel injection timing",
        "decLen": "2",
        "valueMin": "-210",
        "valueMax": "302",
        "units": "°",
        "formula": "(256A+B)/128-210"
    },
    {
        "id": "94",
        "idHex": "5E",
        "decCn": "引擎燃油消耗\n率",
        "decEn": "Engine fuel rate",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "3213",
        "units": "L/h",
        "formula": "(256A+B)/200"
    },
    {
        "id": "95",
        "idHex": "5F",
        "decCn": "符合哪种车辆排放要求 ",
        "decEn": "Emission requirements to which vehicle is designed",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit Encoded"
    },
    {
        "id": "96",
        "idHex": "60",
        "decCn": "",
        "decEn": "PIDs supported [61 - 80]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $61..PID $80]"
    },
    {
        "id": "97",
        "idHex": "61",
        "decCn": "驾驶员请求引\n擎－扭矩百分\n数",
        "decEn": "Driver's demand engine - percent torque",
        "decLen": "1",
        "valueMin": "-125",
        "valueMax": "130",
        "units": "%",
        "formula": "A-125"
    },
    {
        "id": "98",
        "idHex": "62",
        "decCn": "实际引擎－扭\n矩百分数",
        "decEn": "Actual engine - percent torque",
        "decLen": "1",
        "valueMin": "-125",
        "valueMax": "130",
        "units": "%",
        "formula": "A-125"
    },
    {
        "id": "99",
        "idHex": "63",
        "decCn": "引擎参考扭矩 ",
        "decEn": "Engine reference torque",
        "decLen": "2",
        "valueMin": "0",
        "valueMax": "65535",
        "units": "Nm",
        "formula": "256A+B"
    },
    {
        "id": "100",
        "idHex": "64",
        "decCn": "引擎扭矩数据",
        "decEn": "Engine percent torque data",
        "decLen": "5",
        "valueMin": "-125",
        "valueMax": "130",
        "units": "%",
        "formula": "A-125 Idle,B-125 Engine point 1,C-125 Engine point 2,D-125 Engine point 3,E-125 Engine point 4"
    },
    {
        "id": "101",
        "idHex": "65",
        "decCn": "辅助输入/输\n出",
        "decEn": "Auxiliary input / output supported",
        "decLen": "2",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit Encoded"
    },
    {
        "id": "102",
        "idHex": "66",
        "decCn": "空气流量传感\n器（MAF）",
        "decEn": "Mass air flow sensor",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "103",
        "idHex": "67",
        "decCn": "引 擎 冷 却 液 温 度\n（ECT）",
        "decEn": "Engine coolant temperature",
        "decLen": "3",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "104",
        "idHex": "68",
        "decCn": "进气温度（IAT）传感\n器",
        "decEn": "Intake air temperature sensor",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "105",
        "idHex": "69",
        "decCn": "指 令 的 EGR 与\nEGR 误差",
        "decEn": "Commanded EGR and EGR Error",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "106",
        "idHex": "6A",
        "decCn": "指令的柴油机进气\n量控制与相对进气\n量位置",
        "decEn": "Commanded Diesel intake air flow control and relative intake air flow position",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "107",
        "idHex": "6B",
        "decCn": "废气再循环温度",
        "decEn": "Exhaust gas recirculation temperature",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "108",
        "idHex": "6C",
        "decCn": "指令节气门执行元\n件控制与相对节气\n门位置",
        "decEn": "Commanded throttle actuator control and relative throttle position",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "109",
        "idHex": "6D",
        "decCn": "燃油压力控制系统",
        "decEn": "Fuel pressure control system",
        "decLen": "6",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "110",
        "idHex": "6E",
        "decCn": "喷射压力控制系统",
        "decEn": "Injection pressure control system",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "111",
        "idHex": "6F",
        "decCn": "涡轮增压器压缩机进\n气口压力",
        "decEn": "Turbocharger compressor inlet pressure",
        "decLen": "3",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "112",
        "idHex": "70",
        "decCn": "增压压力控制",
        "decEn": "Boost pressure control",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "113",
        "idHex": "71",
        "decCn": "可变涡轮几何增压\n器（VGT）控制",
        "decEn": "Variable Geometry turbo (VGT) control",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "114",
        "idHex": "72",
        "decCn": "指令旁通控制 A 位\n置",
        "decEn": "Wastegate control",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "115",
        "idHex": "73",
        "decCn": "废气压力",
        "decEn": "Exhaust pressure",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "116",
        "idHex": "74",
        "decCn": "涡轮增压器 RPM",
        "decEn": "Turbocharger RPM",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "117",
        "idHex": "75",
        "decCn": "涡轮增压器 A 温度",
        "decEn": "Turbocharger temperature",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "118",
        "idHex": "76",
        "decCn": "涡轮增压器 B 温度",
        "decEn": "Turbocharger temperature",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "119",
        "idHex": "77",
        "decCn": "增压空气中冷器温度\n（CACT）",
        "decEn": "Charge air cooler temperature (CACT)",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "120",
        "idHex": "78",
        "decCn": "废气温度（EGT）B1",
        "decEn": "Exhaust Gas temperature (EGT) Bank 1",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Special PID."
    },
    {
        "id": "121",
        "idHex": "79",
        "decCn": "废气温度（EGT）B2",
        "decEn": "Exhaust Gas temperature (EGT) Bank 2",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Special PID."
    },
    {
        "id": "122",
        "idHex": "7A",
        "decCn": "柴油机微粒过滤器\n（DPF）B1",
        "decEn": "Diesel particulate filter (DPF)",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "123",
        "idHex": "7B",
        "decCn": "柴油机微粒过滤器\n（DPF）B2",
        "decEn": "Diesel particulate filter (DPF)",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "124",
        "idHex": "7C",
        "decCn": "柴油机微粒过滤器\n（DPF）温度",
        "decEn": "Diesel Particulate filter (DPF) temperature",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "125",
        "idHex": "7D",
        "decCn": "NOx NTE控制区域状\n态",
        "decEn": "NOx NTE (Not-To-Exceed) control area status",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "126",
        "idHex": "7E",
        "decCn": "发动机运转时间",
        "decEn": "PM NTE (Not-To-Exceed) control area status",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "127",
        "idHex": "7F",
        "decCn": "PM NTE 控制区域状\n态",
        "decEn": "Engine run time",
        "decLen": "13",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "128",
        "idHex": "80",
        "decCn": "",
        "decEn": "PIDs supported [81 - A0]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $81..PID $A0]"
    },
    {
        "id": "129",
        "idHex": "81",
        "decCn": "AECD#1 - #5 发动机\n运转时间",
        "decEn": "Engine run time for Auxiliary Emissions Control Device(AECD)",
        "decLen": "21",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "130",
        "idHex": "82",
        "decCn": "AECD#6 - #10 发动机\n运转时间",
        "decEn": "Engine run time for Auxiliary Emissions Control Device(AECD)",
        "decLen": "21",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "131",
        "idHex": "83",
        "decCn": "NOx 传感器",
        "decEn": "NOx sensor",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "132",
        "idHex": "84",
        "decCn": "歧管表面温度 ",
        "decEn": "Manifold surface temperature",
        "decLen": "1",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "133",
        "idHex": "85",
        "decCn": "NOx 控制系统",
        "decEn": "NOx reagent system",
        "decLen": "10",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "134",
        "idHex": "86",
        "decCn": "微粒物质（PM）传感\n器",
        "decEn": "Particulate matter (PM) sensor",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "135",
        "idHex": "87",
        "decCn": "进气歧管绝对压力",
        "decEn": "Intake manifold absolute pressure",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "136",
        "idHex": "88",
        "decCn": "",
        "decEn": "SCR Induce System",
        "decLen": "13",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "137",
        "idHex": "89",
        "decCn": "",
        "decEn": "Run Time for AECD #11-#15",
        "decLen": "41",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "138",
        "idHex": "8A",
        "decCn": "",
        "decEn": "Run Time for AECD #16-#20",
        "decLen": "41",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "139",
        "idHex": "8B",
        "decCn": "",
        "decEn": "Diesel Aftertreatment",
        "decLen": "7",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "140",
        "idHex": "8C",
        "decCn": "",
        "decEn": "O2 Sensor (Wide Range)",
        "decLen": "16",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "141",
        "idHex": "8D",
        "decCn": "",
        "decEn": "Throttle Position G",
        "decLen": "1",
        "valueMin": "0",
        "valueMax": "100",
        "units": "%",
        "formula": ""
    },
    {
        "id": "142",
        "idHex": "8E",
        "decCn": "",
        "decEn": "Engine Friction - Percent Torque",
        "decLen": "1",
        "valueMin": "-125",
        "valueMax": "130",
        "units": "%",
        "formula": "A-125"
    },
    {
        "id": "143",
        "idHex": "8F",
        "decCn": "",
        "decEn": "PM Sensor Bank 1 & 2",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "144",
        "idHex": "90",
        "decCn": "",
        "decEn": "WWH-OBD Vehicle OBD System Information",
        "decLen": "3",
        "valueMin": null,
        "valueMax": null,
        "units": "hours",
        "formula": ""
    },
    {
        "id": "145",
        "idHex": "91",
        "decCn": "",
        "decEn": "WWH-OBD Vehicle OBD System Information",
        "decLen": "5",
        "valueMin": null,
        "valueMax": null,
        "units": "hours",
        "formula": ""
    },
    {
        "id": "146",
        "idHex": "92",
        "decCn": "",
        "decEn": "Fuel System Control",
        "decLen": "2",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "147",
        "idHex": "93",
        "decCn": "",
        "decEn": "WWH-OBD Vehicle OBD Counters support",
        "decLen": "3",
        "valueMin": null,
        "valueMax": null,
        "units": "hours",
        "formula": ""
    },
    {
        "id": "148",
        "idHex": "94",
        "decCn": "",
        "decEn": "NOx Warning And Inducement System",
        "decLen": "12",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "152",
        "idHex": "98",
        "decCn": "",
        "decEn": "Exhaust Gas Temperature Sensor",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "153",
        "idHex": "99",
        "decCn": "",
        "decEn": "Exhaust Gas Temperature Sensor",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "154",
        "idHex": "9A",
        "decCn": "",
        "decEn": "Hybrid/EV Vehicle System Data, Battery, Voltage",
        "decLen": "6",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "155",
        "idHex": "9B",
        "decCn": "",
        "decEn": "Diesel Exhaust Fluid Sensor Data",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "156",
        "idHex": "9C",
        "decCn": "",
        "decEn": "O2 Sensor Data",
        "decLen": "17",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "157",
        "idHex": "9D",
        "decCn": "",
        "decEn": "Engine Fuel Rate",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "g/s",
        "formula": ""
    },
    {
        "id": "158",
        "idHex": "9E",
        "decCn": "",
        "decEn": "Engine Exhaust Flow Rate",
        "decLen": "2",
        "valueMin": null,
        "valueMax": null,
        "units": "kg/h",
        "formula": ""
    },
    {
        "id": "159",
        "idHex": "9F",
        "decCn": "",
        "decEn": "Fuel System Percentage Use",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "160",
        "idHex": "A0",
        "decCn": "",
        "decEn": "PIDs supported [A1 - C0]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $A1..PID $C0]"
    },
    {
        "id": "161",
        "idHex": "A1",
        "decCn": "",
        "decEn": "NOx Sensor Corrected Data",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "ppm",
        "formula": ""
    },
    {
        "id": "162",
        "idHex": "A2",
        "decCn": "",
        "decEn": "Cylinder Fuel Rate",
        "decLen": "2",
        "valueMin": null,
        "valueMax": null,
        "units": "mg/stroke",
        "formula": ""
    },
    {
        "id": "163",
        "idHex": "A3",
        "decCn": "",
        "decEn": "Evap System Vapor Pressure",
        "decLen": "9",
        "valueMin": null,
        "valueMax": null,
        "units": "Pa",
        "formula": ""
    },
    {
        "id": "164",
        "idHex": "A4",
        "decCn": "",
        "decEn": "Transmission Actual Gear",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "165",
        "idHex": "A5",
        "decCn": "",
        "decEn": "Diesel Exhaust Fluid Dosing",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": ""
    },
    {
        "id": "166",
        "idHex": "A6",
        "decCn": "",
        "decEn": "Odometer",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "hm",
        "formula": ""
    },
    {
        "id": "192",
        "idHex": "C0",
        "decCn": "",
        "decEn": "PIDs supported [C1 - E0]",
        "decLen": "4",
        "valueMin": null,
        "valueMax": null,
        "units": "",
        "formula": "Bit encoded [A7..D0] == [PID $C1..PID $E0]"
    }
]